name: deployments write

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
      

permissions:
  deployments: write
  contents: read

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: |  
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/QuebecBashing/workflow_run/actions/runs/${{ github.event.inputs.workflow_run_id }}/pending_deployments \
            --input - <<< '{
            "environment_ids": [
              8603319919
            ],
            "state": "approved",
            "comment": "Ship it!"
          }'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
