name: trigger
on:
  pull_request:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pwn"
  b:
    uses: roymani4k/workflow_run/.github/workflows/workflow_call.yml@main
  c:
    uses: QuebecBashing/workflow_run/.github/workflows/test_workflow_call.yml.yml@main
