name: trigger
on:
  create:
  deployment:
  deployment_status:
  merge_group:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  push:
  release:
  workflow_call:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pwn"
